# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Vecorized median
#' 
#' @description Calculate median for each chunks of given vector with customizable chunk size.
#'
#' @param x A numeric vector
#' @param chunkSize An integer
#'
#' @export
vectorizedMedian <- function(x, chunkSize) {
    .Call('baseEncored_vectorizedMedian', PACKAGE = 'baseEncored', x, chunkSize)
}

